name: E2E tests

on:
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [ubuntu-20.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install vfox (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
          sudo apt-get update
          sudo apt-get install vfox
          echo 'eval "$(vfox activate bash)"' >> ~/.bashrc
      
      - name: install vfox (MacOS)
        if: runner.os == 'MacOS'
        run: |
          brew tap version-fox/tap
          brew install vfox
          echo 'eval "$(vfox activate bash)"' >> ~/.bashrc
          echo 'eval "$(vfox activate zsh)"' >> ~/.zshrc
      
      - name: add vfox plugin
        run: |
          vfox add --source https://github.com/yeshan333/vfox-erlang/archive/refs/heads/main.zip erlang
          vfox search erlang 