name: circle_translate

on:
  schedule:
    - cron: "0 16 * * 2"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Update version file
        run: |
          cd .github/workflows
          python get_all_otp_versions.py

      - name: Push updated version file
        run: |
          pwd
          git status -s
          git add .
          git commit -m "chore(versions.txt): update Erlang/OTP version file"
          git push